### ISSUE TITLE
Error message syntax

### ISSUE THREAD

**Issue by SachinMeier** [roostoo/roostoo.github.io#3]
Tiny syntax thing, when I attempt to buy before a competition starts, the error message is "Reject because competition not start yet", and I think this can be improved. 

"Buying will be available once the competition starts" might be better. 

![IMG_E06E706EBAEB-1](https://user-images.githubusercontent.com/46731461/74901738-c7664680-5371-11ea-824c-89f4f85e918d.jpeg)

**Comment by Jolly23** [comment]
The issue has solved
